version: '3.8'
services:
  db:
    image: postgres:14
    environment:
       POSTGRES_USER : DB_AIE321_BIG_DATA
       POSTGRES_PASSWORD : 321bigdatawork
       POSTGRES_DB : AIE321
    ports:
    - "6666:6666"
    volumes:
    - postgres_data
    restart:
volumes:
  postgres_data: